services:
  # Backend API service
  - type: web
    name: whatsapp-supabase-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        fromService:
          type: web
          name: whatsapp-supabase-backend
          envVarKey: PORT
      - key: WHATSAPP_DATA_DIR
        value: ./whatsapp_data
    autoDeploy: true

  # Frontend React app
  - type: web
    name: whatsapp-supabase-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: whatsapp-supabase-backend
          value: https://whatsapp-supabase-backend.onrender.com/api
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_KEY
        sync: false
    autoDeploy: true
